//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgentieImobiliaraEntities : DbContext
    {
        public AgentieImobiliaraEntities()
            : base("name=AgentieImobiliaraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agenti> Agentis { get; set; }
        public virtual DbSet<Agentie> Agenties { get; set; }
        public virtual DbSet<Cartier> Cartiers { get; set; }
        public virtual DbSet<Cereri> Cereris { get; set; }
        public virtual DbSet<DetaliiImobil> DetaliiImobils { get; set; }
        public virtual DbSet<FotoImobil> FotoImobils { get; set; }
        public virtual DbSet<Imobil> Imobils { get; set; }
        public virtual DbSet<Localitate> Localitates { get; set; }
        public virtual DbSet<Oferta> Ofertas { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<UserRol> UserRols { get; set; }
        public virtual DbSet<VideoImobil> VideoImobils { get; set; }
    }
}
