//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaliiImobil
    {
        public int detaliiID { get; set; }
        public int ofertaID { get; set; }
        public string detalii_suplimentare_ro { get; set; }
        public string detalii_suplimentare_en { get; set; }
        public string detalii_suplimentare_fr { get; set; }
        public string detalii_finale_ro { get; set; }
        public string detalii_finale_en { get; set; }
        public string detalii_finale_fr { get; set; }
        public string publica { get; set; }
    
        public virtual Oferta Oferta { get; set; }
    }
}
