//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoImobil
    {
        public int fotoID { get; set; }
        public string NumeFoto { get; set; }
        public string DescriereFoto { get; set; }
        public int ofertaID { get; set; }
        public string img_path { get; set; }
    
        public virtual Oferta Oferta { get; set; }
    }
}
