//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int tokenId { get; set; }
        public int userId { get; set; }
        public string authToken { get; set; }
        public System.DateTime issuedOn { get; set; }
        public System.DateTime expiresOn { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
